#!/bin/bash

[ -z "$2" ] && echo "Run dt-install-sandbox-software to call this script" && exit 1

# This script is called via the dt-install-sandbox-software command.
# Do not run it directly.  Further, this is called prior to the
# sandbox environment being loaded into the shell so any variables
# needed from the defaults.sh (or other env file) must be setup
# manually.

export CSG_SANDBOX=$1  # root of the sandbox
export CSG_TOP=$2      # root of the primary git project
SB_ENV_FILE=$3            # name of the environment file to use
export CSG_NAME=`dirname $CSG_SANDBOX`
[ -z "$SB_ENV_FILE" ] && SB_ENV_FILE=defaults.sh


. $CSG_TOP/sandbox/$SB_ENV_FILE

# Install node if specified with CSG_NODE_VER
[ -n "$CSG_NODE_VER" -a ! -L $CSG_SANDBOX/node ] && dt-get-software -V $CSG_NODE_VER node $CSG_SANDBOX

# Install yarn if specified with CSG_YARN_VER
[ -n "$CSG_YARN_VER" -a ! -L $CSG_SANDBOX/yarn ] && dt-get-software -V $CSG_YARN_VER yarn $CSG_SANDBOX



# Put custom one-time only software installations here (such as git clones of additional repos,
# other software packages that will live in the sandbox, etc...).
#
# Note that there is no sandbox process, other than a first time install, that exeutes this hook.


exit 0
